name: DevSecOps Ultimate Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Security Tools
      run: pip install bandit pip-audit

    - name: Run Bandit SAST Scan
      run: bandit -r . -ll

    - name: Run pip-audit SCA Scan
      run: pip-audit -r requirements.txt

    - name: Run Gitleaks Secrets Scan
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # ՆՈՐ ՔԱՅԼ. Կառուցում ենք Docker Image-ը
    - name: Build Docker Image
      run: docker build -t my-secure-app:latest .

    # ՆՈՐ ՔԱՅԼ. Սկանավորում ենք Docker Image-ը Trivy-ով
    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-secure-app:latest'
        format: 'table'
        exit-code: '1' # Եթե վտանգ գտնի, կոտրի pipeline-ը
        severity: 'CRITICAL,HIGH' # Մեզ հետաքրքիր են միայն լուրջ վտանգները
